server:
  port: 9091
  servlet:
    context-path: /api/v2
  
spring:
  application:
    name: participation-service
  profiles:
    active: local # 기본 프로파일 설정
  config:
    import: application-secret.yml
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}?useUnicode=true&serverTimezone=Asia/Seoul
    username: ${mysql.username}
    password: ${mysql.password}
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true  # DDL 이후 data.sql 실행
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: Asia/Seoul
  sql:
    init:
      mode: always
      encoding: UTF-8
  data:
    mongodb:
      uri: mongodb://${mongodb.username}:${mongodb.password}@{mongodb.host}:{mongodb.port}/search # MongoDB 설정
    elasticsearch:
      client:
        rest:
          uris: ${spring.elasticsearch.uris} # Elasticsearch 설정
          username: ${spring.elasticsearch.username}
          password: ${spring.elasticsearch.password}
    redis:
      host: localhost
      port: 6379
      #host: ${redis.host}
      #port: ${redis.port}

  doc:
    api-docs:
      path: /api/v1/docs
    swagger-ui:
      path: /api/v1/swagger-ui.html

  jackson:
    time-zone: Asia/Seoul
 
management:
  endpoints:
    web:
      exposure:
        include: prometheus  # prometheus 엔드포인트 활성화
  endpoint:
    prometheus:
      enabled: true  # prometheus 메트릭 활성화

solution-service:
  url: https://k11a404.p.ssafy.io:9090/api  # Solution 서비스의 실제 URL
  version: /v1