spring:
  data:
    redis:
      host: my-redis
      port: 6379

otel:
  metrics:
    exporter: none  # Disable metrics exporter
  logs:
    exporter: none  # Disable logs exporter
  traces:
    exporter: otlp  # Use OTLP exporter for traces
  exporter:
    otlp:
      endpoint: "http://43.201.247.235:4317"  # Include 'http://' to make it a valid URL
      protocol: grpc  # Specify the protocol as 'grpc'
  service:
    name: dreamsolution  # Set your service name

minio:
  endpoint: https://k11a404.p.ssafy.io:8998    # participation의 서버에 업로드 (API 포트)

participation-service:
  url: http://k11a404.p.ssafy.io:9091/api
