spring:
  data:
    redis:
      host: localhost
      port: 6379

otel:
  metrics:
    exporter: none  # Disable metrics exporter
  logs:
    exporter: none  # Disable logs exporter
  traces:
    exporter: otlp  # Use OTLP exporter for traces
  exporter:
    otlp:
      endpoint: "http://localhost:16686"  # Include 'http://' to make it a valid URL
      protocol: grpc  # Specify the protocol as 'grpc'
  service:
    name: dreamsolution  # Set your service name

minio:
  endpoint: http://localhost:9000    # 내부 Docker 네트워크용

participation-service:
  url: http://localhost:9091/api
  version: /v2