server:
  port: 8080
  servlet:
    context-path: /api/v1
  
spring:
  profiles:
    active: local # 기본 프로파일 설정
  config:
    import: application-secret.yml
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}?useUnicode=true&serverTimezone=Asia/Seoul
    username: ${mysql.username}
    password: ${mysql.password}
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true  # DDL 이후 data.sql 실행
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: Asia/Seoul
  sql:
    init:
      mode: always
      encoding: UTF-8
  data:
    mongodb:
      uri: mongodb://${mongodb.username}:${mongodb.password}@{mongodb.host}:{mongodb.port}/search # MongoDB 설정
    elasticsearch:
      client:
        rest:
          uris: ${spring.elasticsearch.uris} # Elasticsearch 설정
          username: ${spring.elasticsearch.username}
          password: ${spring.elasticsearch.password}
    redis:
      host: localhost
      port: 6379
      #host: ${redis.host}
      #port: ${redis.port}

  doc:
    api-docs:
      path: /api/v1/docs
    swagger-ui:
      path: /api/v1/swagger-ui.html

  jackson:
    time-zone: Asia/Seoul

minio:
  endpoint: ${minio.endpoint}
  bucket-name: ${minio.bucket-name}
  access-key: ${minio.access-key}
  secret-key: ${minio.secret-key}
  file-manager-user: ${minio.file-manager-user}
  file-manager-password: ${minio.file-manager-password}
