server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dreamsolution?serverTimezone=UTC
    username: solution
    password: onesecondbefore
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      uri: "mongodb://localhost:27017/search" # MongoDB 설정
    elasticsearch:
      client:
        rest:
          uris: "http://localhost:9200" # Elasticsearch 설정
