server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  profiles:
    active: local # 기본 프로파일 설정

  datasource:
    url: jdbc:mysql://localhost:3306/dreamsolution?serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: Asia/Seoul

  data:
    mongodb:
      uri: "mongodb://localhost:27017/search" # MongoDB 설정
    elasticsearch:
      client:
        rest:
          uris: "http://localhost:9200" # Elasticsearch 설정

  doc:
    api-docs:
      path: /api/v1/docs
    swagger-ui:
      path: /api/v1/swagger-ui.html


  jackson:
    time-zone: Asia/Seoul